site_name: Code WiKi
site_url: https://mkouhpayeh.github.io/code-wiki

nav:
  - Home: index.md
  - Fundamentals:
    - Coding Foundation: fundamentals/foundation.md
    - MkDocs Guide: fundamentals/mkdocs.md
    - Shortcuts: fundamentals/shortcut.md
    - SSH Settings: fundamentals/ssh-key.md
    - Windows Command: fundamentals/windows-cmd.md
  - Backend: 
    - Csharp:
      - API:
        - API Server: backend/csharp/api/api.md
        - API Client: backend/csharp/api/api-client.md
        - API Architecture: backend/csharp/api/api-arch.md
        - Anonymous Endpoint: backend/csharp/api/anonymous-endpoint.md
      - Authentication:
        - Authentication: backend/csharp/authentication/auth.md
        - EX Authentication: backend/csharp/authentication/authEx.md
      - EntityFramework:
        - Installation: backend/csharp/entity-framework/ef.md
        - Configuration: backend/csharp/entity-framework/config.md
      - Exception:
        - Exception Customization: backend/csharp/exception/exception-custom.md
        - Exception Handler: backend/csharp/exception/exception-handler.md
        - Exception Filter: backend/csharp/exception/exception-filter.md
      - Mailing:
        - Email Service: backend/csharp/mailing/email-service.md
        - Cloud Service: backend/csharp/mailing/email-cloud-service.md
      - Validation:
        - Validation Attributes: backend/csharp/validation/attrib.md
        - Custom Validation: backend/csharp/validation/custom-attrib.md
    - Python:
      - Extract Firebird: python/extract-firebird.md
  - SQL: 
    - Column Length: sql/col-max-len.md
    - Index Fragmentation: sql/index-frag.md
    - Index Job: sql/index-job.md
    - Index List: sql/index-list.md
    - Index Rebuild: sql/index-rebuild.md
    - Generate Data: sql/sample-data.md
    - Vol Space: sql/vol-space.md
  - Frontend: 
    - CSS Tips: frontend/css-tips.md
    - Bootstrap: frontend/bootstrap.md
    - Loading Page: frontend/loading-overlay.md
    - Markdown: frontend/markdown.md
  - AI: 
    - AI Foundation: ai/foundation.md
  - Automation: 
    - CI/CD GitLab: automation/ci-cd-gitlab.md
    - CI/CD GitHub: automation/ci-cd-github.md
    - Ansible Introduction: automation/ansible-intro.md
    - Ansible Playbook: automation/ansible-playbook.md
  - Docker: 
    - Docker Introduction: docker/docker-intro.md
    - Docker Installation: docs/docker/docker-install.md
    - Docker Usage: docker/docker-useage.md
  - Tools: 
    - Analyze Tools: tools/analyze-tools.md
    - Performance Tools: tools/performance-tools.md
  
theme:
  name: material
  font:
    text: Segoe UI #ui-sans-serif
    code: SFMono-Regular # Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - content.code.copy
  palette:
    #Â Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      

    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode

 
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mahboubeh-kouhpayeh/

copyright: Copyright &copy; 2025 Mahi
